### ISSUE TITLE
Refactor cone definitions

### ISSUE THREAD

**Issue by odow** [odow/MathOptFormat#1]
Following up on https://github.com/JuliaOpt/MathOptInterface.jl/issues/547.

@chriscoey, now is your chance to get in on the ground floor and change the definition of cones in MathOptFormat.

**Comment by chriscoey** [comment]
Not sure there's a good enough reason to have MOF cone definitions differ from MOI definitions. MOI definitions could change a little maybe, but mostly at this point it would be adding new cones there, eg n-dimensional power cones, SOS cones etc. I got no bites on 547 and it's a bit late in the game for those changes. What are your thoughts?

**Comment by odow** [comment]
I guess my biggest pet peeves are having `XXXConeSquare` and `XXXConeTriangle`. Is it necessary to have both?

I think we're free to change MOF to whatever is most suitable long-term. We don't have to be beholden to MOI decisions. I'd rather have a good design we can lock in stone, and progressively make changes to MOI to match, rather than be stuck with MOI design choices.

**Comment by odow** [comment]
@blegat thoughts on the necessity of multiple square/triangle definitions?

**Comment by blegat** [comment]
The triangle definition could be enough but if the user enters
```julia
[x     x-y
 x+y y]
```
then encoding `[x, x+y, x-y, y] in PSDSquare` might be better than encoding `[x, x-y, y] in PSDTriangle` with `2y = 0`.
In the triangle form, you loose structure and you have a linear constraint and you don't know here it comes from.
Also, if the `PSDSquare` constraint has a name, you will loose it when bridging it.
Some bridges may also create unnamed variables (not the case for Square -> Triangle though) is that an issue with MOF ?

**Comment by odow** [comment]
Hmm, and I guess the argument against having only the square definition is verbosity.

> Some bridges may also create unnamed variables (not the case for Square -> Triangle though) is that an issue with MOF ?

Nope. We give any unnamed variables a unique name.

**Comment by odow** [comment]
Closing since it doesn't look like we're changing these.
